<a href="https://colab.research.google.com/github/krufern/Project-1_Coding/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab2_Basic_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title ข้อมูลผู้เรียน
student_name = 'ศิริชัย นกโต' #@param {type:"string"}
school_name = 'สตรีสมุทรปราการ' #@param {type:"string"}
print("ชื่อ - นามสกุล:", student_name)
print("โรงเรียน:", school_name)

ชื่อ - นามสกุล: ศิริชัย นกโต
โรงเรียน: สตรีสมุทรปราการ


# **Basic Python Lab Sheet**

## เนื้อหาประกอบด้วย
1. Basic Data Types (including Lists)
2. Input and Print Functions
3. Operators
4. Conditional Statements (if)
5. Introduction to NumPy

### Slide: [basic python](https://docs.google.com/presentation/d/1kExrO1RfE5l7i6q0dRuuFDrkfM4YUSi6NwNUM2rdvBQ/edit?usp=sharing) | [if](https://docs.google.com/presentation/d/1Llm6REgGDI4mvJ4MfgN9c0uU8ZyyxKVY6apNJU2IQ9o/edit?usp=sharing) | [numpy concept](https://docs.google.com/presentation/d/1qoUhQowgwALcIXytycpeasdLNVnAs7NKPav_apoTqQ4/edit?usp=sharing)
---



### **1. Basic Data Types**
Explore basic data types like integers, floats, strings, booleans, and lists in Python.


In [ ]:
# Examples of Basic Data Types
an_integer = 5
a_float = 3.14
a_string = "Hello, Python!"
a_boolean = True
a_list = [1, 2, 3, 4, 5]

print("Integer:", an_integer)
print("Float:", a_float)
print("String:", a_string)
print("Boolean:", a_boolean)
print("List:", a_list)
print("จำนวนสมาชิกใน List:", len(a_list))


Integer: 5
Float: 3.14
String: Hello, Python!
Boolean: True
List: [1, 2, 3, 4, 5]
จำนวนสมาชิกใน List: 5


#### Exercise 1:
สร้างลิสต์ที่ประกอบด้วยประเภทข้อมูลที่แตกต่างกัน (จำนวนเต็ม, สตริง, จำนวนจริง(จุดทศนิยม)) แล้วแสดงผลข้อมูลทั้งหมดพร้อมชนิดของข้อมูลนั้น


In [ ]:
# code here
b_list = [1,1.50,"sirichai"]
print (b_list)
print (type(b_list[0]),type(b_list[1]),type(b_list[2]))

[1, 1.5, 'sirichai']
<class 'int'> <class 'float'> <class 'str'>


### **2. Input and Print Functions**
Learn to use `input()` for user input and `print()` for output.


In [ ]:
# Input and Print example
user_name = input("Enter your name: ")
print("Hello, " + user_name + "!")


Enter your name: ศิริชัย นกโต
Hello, ศิริชัย นกโต!


#### Exercise 2:
รับข้อมูลเข้าเป็นเลขจำนวนเต็ม 2 ตัว แล้วแสดงเลขจำนวนเต็มทั้งหมด


In [ ]:
# code here
number1 = int(input("กรุณาใส่ตัวเลขตัวที่ 1 :"))
number2 = int(input("กรุณาใส่ตัวเลขตัวที่ 2 :"))
print (number1 +number2)

กรุณาใส่ตัวเลขตัวที่ 1 :2
กรุณาใส่ตัวเลขตัวที่ 2 :3
5


### **3. Operators**
Explore different types of operators in Python.


In [ ]:
# Arithmetic Operators example
a = 10
b = 3

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a // b =", a // b)
print("a % b =", a % b)

a + b = 13
a - b = 7
a * b = 30
a / b = 3.3333333333333335
a // b = 3
a % b = 1


#### Exercise 3:
เขียนโปรแกรมคำนวณหา BMI



In [ ]:
# code here


### **4. Conditional Statements (if)**
Learn how to use `if` statements for decision-making.


In [ ]:
# If statement example
number = int(input("Enter a number: "))
if number > 0:
    print("The number is positive.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


#### Exercise 4:
เขียนโปรแกรมแปลผล BMI

<img src="https://chulalongkornhospital.go.th/kcmh/wp-content/uploads/2022/04/03-14-22-3.jpg" width="400" >

In [ ]:
# code here


#### Exercise 5:
เขียนโปรแกรมรับจำนวนเต็มบวก 3 จำนวน แล้วตรวจสอบว่าสามารถนำไปสร้างเป็นด้านของสามเหลี่ยมได้หรือไม่


In [ ]:
# code here


### **5. Introduction to NumPy**
 NumPy เป็นไลบรารีที่ในภาษา Python ที่ใช้สำหรับการคำนวณทางคณิตศาสตร์  มีความสามารถในการจัดการกับอาเรย์หลายมิติและข้อมูลแบบเมทริกซ์ ทำให้การคำนวณเร็วขึ้นและกระชับขึ้น.

ตัวอย่างข้อดีของการใช้ NumPy:
- NumPy มีความเร็วกว่าการจัดเก็บข้อมูลประเภทลิสต์ของ Python อย่างมากสำหรับการดำเนินการทางคณิตศาสตร์
- มีฟังก์ชันหลากหลายสำหรับการดำเนินการทางคณิตศาสตร์และสถิติ
- จัดการข้อมูลหลายมิติได้อย่างง่ายดาย
- ทำให้การคำนวณทางคณิตศาสตร์ที่ซับซ้อนง่ายขึ้น.


In [ ]:
# Basic Numpy example 1
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("ตัวอย่างการเรียกดูข้อมูลตำแหน่งต่าง ๆ :", arr[0], arr[1], arr[-1])
for data in arr:
  print(data)

ตัวอย่างการสร้างและเรียกใช้

ตัวอย่างการดำเนินการ (operation) ใน numpy

In [ ]:
# Basic NumPy examples 2
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Basic Operations
print("Original Array:", arr)
print("Array + 2:", arr + 2)
print("Array * 2:", arr * 2)
print("Mean of Array:", np.mean(arr))
print("Max of Array:", np.max(arr))

Original Array: [1 2 3 4 5]
Array + 2: [3 4 5 6 7]
Array * 2: [ 2  4  6  8 10]
Mean of Array: 3.0
Max of Array: 5


In [ ]:
# Basic NumPy examples 3
import numpy as np

# การบวกข้อมูลใน array ในตำแหน่งที่ตรงกัน
arr_1 = np.array([10, 20, 30, 40, 50])
arr_2 = np.array([1, 2, 3, 4, 5])
print("arr_1 + arr_2:", arr_1 + arr_2)

# Mean and Standard Deviation
print("Mean of the array:", np.mean(arr))
print("Standard deviation of the array:", np.std(arr))


ตัวอย่างการสร้าง matrix ด้วย numpy

In [ ]:
# Basic NumPy examples 4
import numpy as np

# Creating a 3x3 array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n3x3 Array:\n", matrix)

# Print the second row
print("Second row of the matrix:", matrix[1])

# Sum of all elements
print("Sum of all elements in the matrix:", np.sum(matrix))


3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row of the matrix: [4 5 6]
Sum of all elements in the matrix: 45


#### Exercise 6:
มีคะแนนสอบครั้งที่ 1 และครั้งที่ 2 ของนักเรียนจำนวน 12 คน ถูกเก็บไว้ในลิสต์ชื่อ score1 และ score2 ตามลำดับ
1. จงแปลงเป็น numpy array ชื่อ arr1 และ arr2
2. แสดงผลบวกของคะแนนรวม ซึ่งมาจากคะแนนสอบครั้งที่ 1 รวมกับคะแนนสอบครั้งที่ 2
3. แสดงค่าเฉลี่ยของคะแนนสอบแต่ละครั้ง และคะแนนรวม
4. แสดงคะแนนของนักเรียนที่มากกว่าค่าเฉลี่ย และนับว่ามีกี่คน


In [ ]:
# code here
score1 = [8, 7.5, 4, 10, 9.5, 9, 7, 8.5, 7, 8, 6.5, 9]
score2 = [7, 7, 5.5, 8.5, 9, 9, 6, 6.5, 7, 8, 7.5, 10]

